name: Nuclei Scan with Artifact Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Clone Optiv's Nuclei Templates Repository
    - name: Clone Optiv Nuclei Templates
      run: |
        git clone https://github.com/optiv/nuclei-templates custom-templates

    # Step 3: Run Nuclei Scan
    - name: Run Nuclei Scan
      uses: projectdiscovery/nuclei-action@main
      with:
        target: targets.txt                  # File containing target URLs
        templates: custom-templates/         # Path to cloned custom templates
        severity: critical,high              # Filter by severity (optional)
        json-export: nuclei-results.json     # Export results to JSON

    # Step 4: Upload Scan Results as an Artifact
    - name: Upload Scan Results
      uses: actions/upload-artifact@v4       # Updated version of upload-artifact action
      with:
        name: nuclei-results                 # Name of the artifact
        path: nuclei-results.json            # Path to the file or directory to upload
