name: Nuclei Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Clone Private Nuclei Templates
    - name: Clone Private Nuclei Templates
      run: git clone https://github.com/Akokonunes/Private-Nuclei-Templates private-templates

    # Step 3: Clone ProjectDiscovery Nuclei Templates
    - name: Clone ProjectDiscovery Nuclei Templates
      run: git clone https://github.com/projectdiscovery/nuclei-templates default-templates

    # Step 4: Verify Templates Exist
    - name: Check Template Directories
      run: |
        ls -l private-templates/
        ls -l default-templates/

    # Step 5: Run Nuclei Scan
    - name: Run Nuclei Scan
      uses: projectdiscovery/nuclei-action@main
      with:
        target: .github/workflows/targets.txt  # Path to targets.txt in the same directory as the YAML file
        templates: |
          private-templates/
          default-templates/
        severity: critical,high                # Filter by severity (optional)
        json-export: nuclei-results.json       # Export results to JSON

    # Step 6 (Optional): Upload Scan Results as Artifact
    - name: Upload Scan Results
      uses: actions/upload-artifact@v4
      with:
        name: nuclei-results
        path: nuclei-results.json
