name: Nuclei - Vulnerability Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual execution

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Nuclei Templates
        run: |
          mkdir -p ~/.nuclei-templates
          git clone --depth 1 https://github.com/projectdiscovery/nuclei-templates ~/.nuclei-templates
          git clone --depth 1 https://github.com/1ndianl33t/Nuclei-Templates ~/.nuclei-templates/custom-1ndianl33t
          git clone --depth 1 https://github.com/optiv/nuclei-templates ~/.nuclei-templates/custom-optiv

      - name: Nuclei - Vulnerability Scan
        id: nuclei_scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: https://juice-shop.herokuapp.com
          template-path: ~/.nuclei-templates

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuclei.log
          path: nuclei.log

      - name: GitHub Security Dashboard Alerts update
        uses: github/codeql-action/upload-sarif@v3
        if: steps.nuclei_scan.outputs.sarif_exists == 'true'
        with:
          sarif_file: nuclei.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
