name: Nuclei Scan with Multiple Template Sources

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Clone Private Nuclei Templates Repository
    - name: Clone Private Nuclei Templates
      run: |
        git clone https://github.com/Akokonunes/Private-Nuclei-Templates private-templates

    # Step 3: Clone ProjectDiscovery Nuclei Templates Repository
    - name: Clone ProjectDiscovery Nuclei Templates
      run: |
        git clone https://github.com/projectdiscovery/nuclei-templates default-templates

    # Step 4: Run Nuclei Scan with Both Template Sources
    - name: Run Nuclei Scan
      uses: projectdiscovery/nuclei-action@main
      with:
        target: targets.txt                  # File containing target URLs
        templates: |
          private-templates/                 # Path to Private Nuclei Templates
          default-templates/                 # Path to ProjectDiscovery Nuclei Templates
        severity: critical,high              # Filter by severity (optional)
        json-export: nuclei-results.json     # Export results to JSON

    # Step 5 (Optional): Upload Scan Results as an Artifact
    - name: Upload Scan Results
      uses: actions/upload-artifact@v4       # Updated version of upload-artifact action
      with:
        name: nuclei-results                 # Name of the artifact
        path: nuclei-results.json            # Path to the file or directory to upload
