name: Nuclei Scan with Custom Templates

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Clone Optiv's Nuclei Templates Repository
    - name: Clone Optiv Nuclei Templates
      run: |
        git clone https://github.com/optiv/nuclei-templates custom-templates

    # Step 3: Run Nuclei with Both Default and Custom Templates
    - name: Run Nuclei Scan
      uses: projectdiscovery/nuclei-action@main
      with:
        target: targets.txt                  # File containing target URLs
        templates: |
          /home/runner/nuclei-templates/     # Default ProjectDiscovery templates
          custom-templates/                  # Custom Optiv templates
        severity: critical,high              # Filter by severity (optional)
        json-export: nuclei-results.json     # Export results to JSON (optional)

    # Step 4 (Optional): Upload Results as an Artifact
    - name: Upload Scan Results
      uses: actions/upload-artifact@v3
      with:
        name: nuclei-results
        path: nuclei-results.json
